### ISSUE TITLE
Arbitrary Integers

### ISSUE THREAD

**Issue by darleybarreto** [npars/arbintrary#1]
Hi @npars, nice job in this PoC! I have a question about arbitrary integers (N > 128). Is it possible to implement them as a crate (outside rustc)? I gave a look at your implementation and I must say I thought it would be a lot simpler, that is, without manually implementing for all `0 <= N <= 127`, is that a limitation of current stable const generics?

PS: I am definitely not an expert in Rust.

Thanks,

**Comment by npars** [comment]
Hey @darleybarreto, there's a couple limitations that prevent what would basically be a "one and done" solution to this problem.

* The backing type for each instance must be declared based on the bit size of the integer. We currently choose the smallest primitive that fits the bit size. Alternatively we could just back everything by u128/i128 for N <= 128 and accept the wasted space. Or we could do something generic like have an array of integers that changes size based on the bit size, this would probably be the most robust solution but would require the most complex implementation.
* Generic const currently doesn't allow a where clause for doing trait implementations. For instance, something like the following is _not_ valid:
   ```rust
    impl<const N: usize, const M: usize> From<uint<M>> for uint<N> where  M < N {
        fn from(value: uint<M>) -> Self {
            Self(value.0.into()).mask()
        }
    }
   ```
   Because this functionality is not yet supported, we need to implement the trait for every valid combination of N and M consts.

For values of N > 128, this is definitely possible and is already done in crates like [uint](https://crates.io/crates/uint). I think for this repo we might want to limit N > 128 to multiples of 128 or something, just to reduce the explosion of required trait implementations.

**Comment by darleybarreto** [comment]
Oh, I see. Thanks for your thorough response!

**Comment by npars** [comment]
Closing this issue. Please feel free to raise another issue if there's something specific you'd like to see implemented.
